version: "3.8"

services:
  backend-election:
    container_name: backend-election
    build: .
    ports:
      - ${PORT}:${PORT}

    depends_on:
      - postgresdb
    volumes:
      - .:/app
    restart: always
