version: "3.8"

services:
  backend-election:
    container_name: backend-election
    build: .
    ports:
      - ${PORT}:${PORT}
      - 9100:9100

    depends_on:
      - postgresdb
    volumes:
      - .:/app
    restart: always

  postgresdb:
    container_name: be-election-postgres
    image: postgres
    ports:
      - "5433:${DB_POSTGRES_PORT}"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_POSTGRES_NAME}

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres-exporter
    ports:
      - 9187:9187
    environment:
      DATA_SOURCE_NAME: "${DB_POSTGRES}"
    depends_on:
      - postgresdb

volumes:
  postgresdata:
